tattootracker/app_tattootracker/urls.py
from django.urls import path
from .views import (upload_tattoo, view_tattoos, upload_handler, edit_tattoo, home_view, public_gallery,
                    signup_success, delete_tattoo, delete_tattoo_confirm)
from . import views

urlpatterns = [
    path('', home_view, name='home'),
    path('upload_tattoo/', upload_tattoo, name='upload_tattoo'),
    path('view_tattoos/', view_tattoos, name='view_tattoos'),
    path('upload_handler/', upload_handler, name='upload_handler'),
    path('edit_tattoo/<int:tattoo_id>/', edit_tattoo, name='edit_tattoo'),
    path('delete_tattoo/<int:tattoo_id>/', delete_tattoo, name='delete_tattoo'),
    path('delete_tattoo_confirm/<int:tattoo_id>/', delete_tattoo_confirm, name='delete_tattoo_confirm'),
    path('public_gallery/', views.public_gallery, name='public_gallery'),
    path('signup-success/', views.signup_success, name='signup_success'),
]

tattootracker/app_users/urls.py
from django.urls import path
from .views import SignUpView, LoginView, LogoutView

app_name = 'app_users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

tattootracker/project_tattootracker/urls.py
from app_tattootracker import views
from app_tattootracker.views import upload_tattoo
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


app_name = 'project_tattootracker'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('api/', include('app_users.urls')),
    path('login/', TemplateView.as_view(template_name='login.html'), name='login'),
    path('signup/', TemplateView.as_view(template_name='signup.html'), name='signup'),
    path('upload_tattoo/', upload_tattoo, name='upload_tattoo'),
    path('app_tattootracker/', include('app_tattootracker.urls')),
    path('users/', include('app_users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tattootracker/app_tattootracker/models.py
from django.db import models
from django.contrib.auth.models import User


class Tattoo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tattoos')
    image = models.ImageField(upload_to='tattoos/')
    body_part = models.CharField(max_length=100)
    artist_name = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField()
    is_public = models.BooleanField(default=False)
    title = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.user.username}'s tattoo on {self.body_part}"

tattootracker/app_tattootracker/forms.py
from django import forms
from .models import Tattoo


class TattooForm(forms.ModelForm):
    class Meta:
        model = Tattoo
        fields = ['image', 'body_part', 'artist_name', 'date', 'description', 'is_public']

tattootracker/app_tattootracker/views.py
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import TattooForm
from django.shortcuts import render, get_object_or_404, redirect
from .models import Tattoo


def home(request):
    tattoo = Tattoo.objects.first()
    return render(request, 'base.html', {'tattoo': tattoo})


def signup_success(request):
    return render(request, 'signup_success.html')


@login_required
def upload_tattoo(request):
    if request.method == 'POST':
        form = TattooForm(request.POST, request.FILES)
        if form.is_valid():
            tattoo = form.save(commit=False)
            tattoo.user = request.user
            if 'is_public' in request.POST:
                tattoo.is_public = True
            tattoo.save()
            return redirect('view_tattoos')
    else:
        form = TattooForm()
    return render(request, 'upload_tattoo.html', {'form': form})


def view_tattoos(request):
    if request.user.is_authenticated:
        tattoos = Tattoo.objects.filter(user=request.user)
        return render(request, 'view_tattoos.html', {'tattoos': tattoos})
    else:
        return redirect('public_gallery')


@login_required
def upload_handler(request):
    if request.method == 'POST' and request.FILES:
        form = TattooForm(request.POST, request.FILES)
        if form.is_valid():
            new_tattoo = form.save(commit=False)
            new_tattoo.user = request.user
            new_tattoo.save()
            return JsonResponse({'message': 'Success'}, status=200)
        else:
            return JsonResponse({'error': 'Form is not valid'}, status=400)
    return JsonResponse({'error': 'This method is not allowed'}, status=405)


def edit_tattoo(request, tattoo_id):
    tattoo = get_object_or_404(Tattoo, pk=tattoo_id)
    if request.method == 'POST':
        form = TattooForm(request.POST, request.FILES, instance=tattoo)
        if form.is_valid():
            form.save()
            return redirect('view_tattoos')
    else:
        form = TattooForm(instance=tattoo)
    return render(request, 'edit_tattoo.html', {'form': form, 'tattoo': tattoo})


def home_view(request):
    return render(request, 'base.html')


def public_gallery(request):
    public_tattoos = Tattoo.objects.filter(is_public=True)
    return render(request, 'public_gallery.html', {'tattoos': public_tattoos})


def delete_tattoo(request, tattoo_id):
    tattoo = get_object_or_404(Tattoo, pk=tattoo_id)
    if request.method == 'POST':
        tattoo.delete()
        return redirect('view_tattoos')
    return render(request, 'confirm_delete.html', {'tattoo': tattoo})


def delete_tattoo_confirm(request, tattoo_id):
    tattoo = get_object_or_404(Tattoo, pk=tattoo_id)
    if request.method == 'POST':
        tattoo.delete()
        return redirect('view_tattoos')
    return render(request, 'confirm_delete.html', {'tattoo': tattoo})

tattootracker/app_users/views.py
from django.contrib.auth import login, logout, authenticate
from rest_framework.authtoken.models import Token
from django.contrib.auth.models import User
from rest_framework import status, views
from rest_framework.response import Response
from django.shortcuts import redirect, render


class SignUpView(views.APIView):
    def post(self, request, *args, **kwargs):
        username = request.data.get('username')
        password = request.data.get('password')
        if not User.objects.filter(username=username).exists():
            user = User.objects.create_user(username=username, password=password)
            # Automatically log in the user
            login(request, user)
            token, _ = Token.objects.get_or_create(user=user)
            print("User signed up successfully")  # Add debug statement
            return redirect('/')
            # return Response({'token': token.key}, status=status.HTTP_201_CREATED)
        else:
            return Response({'error': 'Username already exists'}, status=status.HTTP_400_BAD_REQUEST)


class LoginView(views.APIView):
    def post(self, request, *args, **kwargs):
        username = request.data.get('username')
        password = request.data.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            token, _ = Token.objects.get_or_create(user=user)
            return Response({'token': token.key}, status=status.HTTP_200_OK)
        return Response({'error': 'Invalid Credentials'}, status=status.HTTP_400_BAD_REQUEST)


class LogoutView(views.APIView):
    def post(self, request):
        logout(request)
        return Response(status=status.HTTP_204_NO_CONTENT)


class SignUpSuccessView(views.APIView):
    def post(self, request, *args, **kwargs):
        username = request.data.get('username')
        password = request.data.get('password')
        if not User.objects.filter(username=username).exists():
            user = User.objects.create_user(username=username, password=password)
            login(request, user)
            token, _ = Token.objects.get_or_create(user=user)
            return Response({'token': token.key}, status=status.HTTP_200_OK)

tattootracker/app_tattootracker/templates/base.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Home Page{% endblock %}
{% block content %}
<div class="carousel-inner" id="carouselSlides">
    <div class="slides">
        <img src="{% static 'images/home1.png' %}" alt="Image 1">
        <img src="{% static 'images/home2.png' %}" alt="Image 2">
        <img src="{% static 'images/home3.png' %}" alt="Image 3">
        <img src="{% static 'images/home1.png' %}" alt="Image 4">
        <img src="{% static 'images/home2.png' %}" alt="Image 5">
        <img src="{% static 'images/home3.png' %}" alt="Image 6">
    </div>
    <div class="buttons">
        <button onclick="prevSlide()">Prev</button>
        <button onclick="nextSlide()">Next</button>
    </div>
</div>
<script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

tattootracker/app_tattootracker/templates/confirm_delete.html
{% extends 'index.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <h2>Confirm Delete</h2>
</head>
<body>
<div class="deletion">
    <p>Are you sure you want to delete the tattoo?</p>
    <form action="{% url 'delete_tattoo_confirm' tattoo.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
        <a href="{% url 'edit_tattoo' tattoo.id %}">Cancel</a>
    </form>
</div>
</body>
</html>
{% endblock %}

tattootracker/app_tattootracker/templates/edit_tattoo.html
{% extends 'base.html' %}
{% block content %}
<h2>Edit Tattoo</h2>
<div class="editor">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
        <a href="{% url 'delete_tattoo' tattoo.id %}" class="btn btn-danger">Delete</a>
    </form>
</div>
{% endblock %}

tattootracker/app_tattootracker/templates/images.html
{% extends 'index.html' %}
{% block content %}
{% for tattoo in user.tattoos.all %}
    <div>
        <img src="{{ tattoo.image.url }}" alt="Tattoo image on {{ tattoo.body_part }}">
        <p>Artist: {{ tattoo.artist_name }}</p>
        <p>Date: {{ tattoo.date }}</p>
        <p>Description: {{ tattoo.description }}</p>
    </div>
{% endfor %}
{% endblock %}

tattootracker/app_tattootracker/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RM Tattoo Tracker</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    <hr style="width:100%;text-align:left;margin-left:0">

    <header id="Heading">
        <h1>Tattoo Tracker</h1>
    </header>
    <hr style="width:100%;text-align:left;margin-left:0">
    <nav id="auth" class="auth">
        <button class="btn" onclick="location.href='{% url 'login' %}'">Login</button>
        <button class="btn" onclick="location.href='{% url 'signup' %}'">Sign Up</button>
        <button onclick="checkLogin()">Check Login State</button>
        <button onclick="logout()">Logout</button>
    </nav>
    <hr style="width:100%;text-align:left;margin-left:0">
    <div class="navigation">
        <a href="{% url 'home' %}" class="btn">Home</a>
        <a href="{% url 'upload_tattoo' %}" class="btn btn-primary">Upload New Tattoo</a>
        <a href="{% url 'view_tattoos' %}" class="btn btn-primary">View Tattoos</a>
        <a href="{% url 'public_gallery' %}" class="btn btn-primary">Public Gallery</a>
    </div>
    <hr style="width:100%;text-align:left;margin-left:0">
    {% if tattoo %}
        <a href="{% url 'edit_tattoo' tattoo.id %}">View Details and Edit</a>
    {% else %}
        <p></p>
    {% endif %}
    {% block content %}
    {% endblock %}

    <script src="{% static 'js/auth.js' %}"></script>
</body>
<footer>
    <h3>By: Rylei Mindrum | A02352206</h3>
</footer>
</html>

tattootracker/app_tattootracker/templates/login.html
{% extends 'index.html' %}
{% block content %}
<div class="temps">
<h2>Login</h2>
<form id="loginForm" onsubmit="login(event)">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required>
    <button type="submit">Login</button>
    <p>  </p>
    <div class="boxes">
        <p>Dont Have An Account?</p>
        <button class="btn" onclick="location.href='{% url 'signup' %}'">Sign Up</button>
    </div>
</form>
{% endblock %}
</div>

tattootracker/app_tattootracker/templates/public_gallery.html
{% extends 'index.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>Public Gallery</title>
</head>
<body>
    <h2>Public Gallery</h2>
    <div class="gallery">
        {% for tattoo in tattoos %}
            <img src="{{ tattoo.image.url }}" alt="{{ tattoo.title }}">
        {% endfor %}
    </div>
    <p>  </p>
    {% if not request.user.is_authenticated %}
    <div class="boxes">
        <p>Want to Upload your own Tattoos?</p>
        <button class="btn" onclick="location.href='{% url 'login' %}'">Login</button>
        <button class="btn" onclick="location.href='{% url 'signup' %}'">Sign Up</button>
    </div>
    {% endif %}
</body>
{% endblock %}
</html>

tattootracker/app_tattootracker/templates/signup.html
{% extends 'index.html' %}
{% block content %}
<div class="temps">
<h2>Create An Account</h2>
<form id="signupForm" onsubmit="signup(event)">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required>
    <button type="submit">Sign Up</button>
    <p>  </p>
    <div class="boxes">
        <p>Already Have An Account?</p>
        <button class="btn" onclick="location.href='{% url 'login' %}'">Login</button>
    </div>
</form>
{% endblock %}
</div>

tattootracker/app_tattootracker/templates/upload_tattoo.html
{% extends 'index.html' %}
{% block content %}
<h2>Upload a New Tattoo</h2>
<div class="uploader" id="upload-form" data-upload-url="{% url 'upload_handler' %}">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <label for="id_is_public">Make Public:</label>
        <input type="checkbox" id="id_is_public" name="is_public">
        <button type="submit">Upload Tattoo</button>
    </form>
</div>
{% endblock %}

tattootracker/app_tattootracker/templates/view_tattoos.html
{% extends 'index.html' %}
{% block content %}

{% if tattoos %}
    {% for tattoo in tattoos %}
        <h2>My Tattoos</h2>
        <div class="viewer">
            <img src="{{ tattoo.image.url }}" alt="Tattoo">
            <p>{{ tattoo.description }}</p>
            <a href="{% url 'edit_tattoo' tattoo.id %}">Edit</a>
        </div>
    {% endfor %}
{% else %}
    <p></p>
{% endif %}
{% endblock %}